name: "${name}"
main: "${group}.Pl3xMapBanners"
version: "${version}"
api-version: "${apiVersion}"
load: "POSTWORLD"
authors: ${authors}
description: "${description}"
website: "${website}"

softdepend:
  - Pl3xMap

permissions:
  pl3xmap.banners.admin:
    description: Gives access to add/remove banners by clicking
    default: op