name: "${name}"
main: "${group}.Pl3xMapBanners"
version: "${version}"
api-version: "1.20"
load: "POSTWORLD"
authors: ${authors}
description: "${description}"
website: "${website}"
softdepend:
  - Pl3xMap

permissions:
  pl3xmap.banners.admin:
    description: Gives access to add/remove banners by clicking
    default: true
